spring:
  application:
    name: demo
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true

    database: POSTGRESQL
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:10000/benchmarkDB
    username: application
    password: application
    driver-class-name: org.postgresql.Driver
    name: benchmarkDB
  data:
    mongodb:
      uri: mongodb://localhost:10002/
      port: 10002
      database: benchmarkDB
    neo4j:
      uri: bolt://localhost:10003/benchmarkDB
      username: neo4j
      password: admin

server:
  port: 9000